bits 64

global _start

_start:
	mov	rax, main
	call	rax
	mov	rax, exit
	call	rax
; this code was generated by a tool.
bits 64

puts:
push rbp
mov rbp, rsp
push rdi
xor rax, rax
push rax
jmp puts_L1
puts_L0:
mov rax, putch
push rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
pop rax
call rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
push rax
mov rax, 1
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
mov [rdi], rax
puts_L1:
mov rax, rbp
mov rdi, 16
sub rax, rdi
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
xor rax, rax
mov al, [rdi]
pop rdi
mov [rdi], rax
test rax, rax
jnz puts_L0
mov rax, 0
mov rsp, rbp
pop rbp
ret
mov rsp, rbp
pop rbp
ret
nextarg:
push rbp
mov rbp, rsp
push rdi
xor rax, rax
push rax
jmp nextarg_L3
nextarg_L2:
mov rax, rbp
mov rdi, 8
sub rax, rdi
push rax
mov rax, 1
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
mov [rdi], rax
nextarg_L3:
mov rax, 0
push rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
xor rax, rax
mov al, [rdi]
pop rdi
mov [rdi], rax
pop rdi
xor rdx, rdx
cmp rax, rdi
setne dl
mov rax, rdx
test rax, rax
jnz nextarg_L2
mov rax, 1
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
mov rsp, rbp
pop rbp
ret
mov rsp, rbp
pop rbp
ret
main:
push rbp
mov rbp, rsp
push rdi
push rsi
xor rax, rax
push rax
push rax
push rax
push rax
push rax
push rax
mov rax, rbp
mov rdi, 64
sub rax, rdi
push rax
mov rax, brk
push rax
mov rax, 1
neg rax
push rax
pop rdi
pop rax
call rax
pop rdi
mov [rdi], rax
mov rax, brk
push rax
mov rax, 8192
push rax
mov rax, rbp
mov rdi, 64
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
push rax
pop rdi
pop rax
call rax
mov rax, 3
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
pop rdi
xor rdx, rdx
cmp rax, rdi
setne dl
mov rax, rdx
test rax, rax
jz main_L4
mov rax, puts
push rax
jmp main_L7
main_L6:
db "usage: copy file destfile"
db 0
main_L7:
mov rax, main_L6
push rax
pop rdi
pop rax
call rax
mov rax, putch
push rax
mov rax, 10
push rax
pop rdi
pop rax
call rax
mov rax, 0
mov rsp, rbp
pop rbp
ret
jmp main_L5
main_L4:
main_L5:
mov rax, rbp
mov rdi, 24
sub rax, rdi
push rax
mov rax, nextarg
push rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
pop rax
call rax
pop rdi
mov [rdi], rax
mov rax, rbp
mov rdi, 32
sub rax, rdi
push rax
mov rax, nextarg
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
pop rax
call rax
pop rdi
mov [rdi], rax
mov rax, rbp
mov rdi, 40
sub rax, rdi
push rax
mov rax, open
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
push rax
mov rax, 0
push rax
pop rsi
pop rdi
pop rax
call rax
pop rdi
mov [rdi], rax
mov rax, 0
push rax
mov rax, rbp
mov rdi, 40
sub rax, rdi
mov rax, [rax]
pop rdi
xor rdx, rdx
cmp rax, rdi
setle dl
mov rax, rdx
test rax, rax
jz main_L8
mov rax, puts
push rax
jmp main_L11
main_L10:
db "Failed to open "
db 0
main_L11:
mov rax, main_L10
push rax
pop rdi
pop rax
call rax
mov rax, puts
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
pop rax
call rax
mov rax, putch
push rax
pop rax
call rax
mov rax, 0
mov rsp, rbp
pop rbp
ret
jmp main_L9
main_L8:
main_L9:
mov rax, rbp
mov rdi, 48
sub rax, rdi
push rax
mov rax, creat
push rax
mov rax, rbp
mov rdi, 32
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
pop rax
call rax
pop rdi
mov [rdi], rax
mov rax, 0
push rax
mov rax, rbp
mov rdi, 40
sub rax, rdi
mov rax, [rax]
pop rdi
xor rdx, rdx
cmp rax, rdi
setle dl
mov rax, rdx
test rax, rax
jz main_L12
mov rax, puts
push rax
jmp main_L15
main_L14:
db "Failed to open "
db 0
main_L15:
mov rax, main_L14
push rax
pop rdi
pop rax
call rax
mov rax, puts
push rax
mov rax, rbp
mov rdi, 32
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
pop rax
call rax
mov rax, putch
push rax
pop rax
call rax
mov rax, 0
mov rsp, rbp
pop rbp
ret
jmp main_L13
main_L12:
main_L13:
jmp main_L17
main_L16:
mov rax, write
push rax
mov rax, rbp
mov rdi, 48
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 64
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 56
sub rax, rdi
mov rax, [rax]
push rax
pop rdx
pop rsi
pop rdi
pop rax
call rax
main_L17:
mov rax, 0
push rax
mov rax, rbp
mov rdi, 56
sub rax, rdi
push rax
mov rax, read
push rax
mov rax, rbp
mov rdi, 40
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 64
sub rax, rdi
mov rax, [rax]
push rax
mov rax, 8192
push rax
pop rdx
pop rsi
pop rdi
pop rax
call rax
pop rdi
mov [rdi], rax
pop rdi
xor rdx, rdx
cmp rax, rdi
setg dl
mov rax, rdx
test rax, rax
jnz main_L16
mov rax, close
push rax
mov rax, rbp
mov rdi, 40
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
pop rax
call rax
mov rax, close
push rax
mov rax, rbp
mov rdi, 48
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
pop rax
call rax
mov rax, 0
mov rsp, rbp
pop rbp
ret
mov rsp, rbp
pop rbp
ret

open:
	mov rax, 0
	int 132
	ret
creat:
        mov rax, 1
        int 132
	ret
close:
	mov rax, 2
	int 132
	ret
read:
	mov rax, 3
	int 132
	ret
write:
	mov rax, 4
	int 132
	ret

fgetch:
	mov rax, 5
	int 132
	ret
fputch:
	mov rax, 6
	int 132
	ret
seek:
	mov rax, 7
	int 132
	ret
getch:
	mov rax, 8
	int 132
	ret
putch:
	mov rax, 9
	int 132
	ret
getcwd:
	mov rax, 10
	int 132
	ret
getdents64:
	mov rax, 11
	int 132
	ret
rename:
	mov rax, 12
	int 132
	ret
mkdir:
	mov rax, 13
	int 132
	ret
rmdir:
	mov rax, 14
	int 132
	ret
chdir:
	mov rax, 15
	int 132
	ret
unlink:
	mov rax, 16
	int 132
	ret
exec:
	mov rax, 17
	int 132
	ret
fork:
	mov rax, 18
	int 132
	ret
waitpid:
	mov rax, 19
	int 132
	ret
dup2:
	mov rax, 20
	int 132
	ret
brk:
	mov rax, 21
	int 132
	ret
mmap:
	mov rax, 22
	int 132
	ret
exit:
	mov rax, 23
	int 132
	ret

