; this code was generated by a tool.
bits 64

puts:
push rbp
mov rbp, rsp
push rdi
xor rax, rax
push rax
jmp puts_L1
puts_L0:
mov rax, putch
push rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
pop rax
call rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
push rax
mov rax, 1
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
mov [rdi], rax
puts_L1:
mov rax, rbp
mov rdi, 16
sub rax, rdi
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
xor rax, rax
mov al, [rdi]
pop rdi
mov [rdi], rax
test rax, rax
jnz puts_L0
mov rax, 0
mov rsp, rbp
pop rbp
ret
mov rsp, rbp
pop rbp
ret
nextarg:
push rbp
mov rbp, rsp
push rdi
xor rax, rax
push rax
jmp nextarg_L3
nextarg_L2:
mov rax, rbp
mov rdi, 8
sub rax, rdi
push rax
mov rax, 1
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
mov [rdi], rax
nextarg_L3:
mov rax, 0
push rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
xor rax, rax
mov al, [rdi]
pop rdi
mov [rdi], rax
pop rdi
xor rdx, rdx
cmp rax, rdi
setne dl
mov rax, rdx
test rax, rax
jnz nextarg_L2
mov rax, 1
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
mov rsp, rbp
pop rbp
ret
mov rsp, rbp
pop rbp
ret
main:
push rbp
mov rbp, rsp
push rdi
push rsi
xor rax, rax
push rax
push rax
push rax
push rax
push rax
push rax
mov rax, rbp
mov rdi, 64
sub rax, rdi
push rax
mov rax, brk
push rax
mov rax, 1
neg rax
push rax
pop rdi
pop rax
call rax
pop rdi
mov [rdi], rax
mov rax, brk
push rax
mov rax, 8192
push rax
mov rax, rbp
mov rdi, 64
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
push rax
pop rdi
pop rax
call rax
mov rax, 3
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
pop rdi
xor rdx, rdx
cmp rax, rdi
setne dl
mov rax, rdx
test rax, rax
jz main_L4
mov rax, puts
push rax
jmp main_L7
main_L6:
db "usage: copy file destfile"
db 0
main_L7:
mov rax, main_L6
push rax
pop rdi
pop rax
call rax
mov rax, putch
push rax
mov rax, 10
push rax
pop rdi
pop rax
call rax
mov rax, 0
mov rsp, rbp
pop rbp
ret
jmp main_L5
main_L4:
main_L5:
mov rax, rbp
mov rdi, 24
sub rax, rdi
push rax
mov rax, nextarg
push rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
pop rax
call rax
pop rdi
mov [rdi], rax
mov rax, rbp
mov rdi, 32
sub rax, rdi
push rax
mov rax, nextarg
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
pop rax
call rax
pop rdi
mov [rdi], rax
mov rax, rbp
mov rdi, 40
sub rax, rdi
push rax
mov rax, open
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
push rax
mov rax, 0
push rax
pop rsi
pop rdi
pop rax
call rax
pop rdi
mov [rdi], rax
mov rax, 0
push rax
mov rax, rbp
mov rdi, 40
sub rax, rdi
mov rax, [rax]
pop rdi
xor rdx, rdx
cmp rax, rdi
setle dl
mov rax, rdx
test rax, rax
jz main_L8
mov rax, puts
push rax
jmp main_L11
main_L10:
db "Failed to open "
db 0
main_L11:
mov rax, main_L10
push rax
pop rdi
pop rax
call rax
mov rax, puts
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
pop rax
call rax
mov rax, putch
push rax
pop rax
call rax
mov rax, 0
mov rsp, rbp
pop rbp
ret
jmp main_L9
main_L8:
main_L9:
mov rax, rbp
mov rdi, 48
sub rax, rdi
push rax
mov rax, creat
push rax
mov rax, rbp
mov rdi, 32
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
pop rax
call rax
pop rdi
mov [rdi], rax
mov rax, 0
push rax
mov rax, rbp
mov rdi, 40
sub rax, rdi
mov rax, [rax]
pop rdi
xor rdx, rdx
cmp rax, rdi
setle dl
mov rax, rdx
test rax, rax
jz main_L12
mov rax, puts
push rax
jmp main_L15
main_L14:
db "Failed to open "
db 0
main_L15:
mov rax, main_L14
push rax
pop rdi
pop rax
call rax
mov rax, puts
push rax
mov rax, rbp
mov rdi, 32
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
pop rax
call rax
mov rax, putch
push rax
pop rax
call rax
mov rax, 0
mov rsp, rbp
pop rbp
ret
jmp main_L13
main_L12:
main_L13:
jmp main_L17
main_L16:
mov rax, write
push rax
mov rax, rbp
mov rdi, 48
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 64
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 56
sub rax, rdi
mov rax, [rax]
push rax
pop rdx
pop rsi
pop rdi
pop rax
call rax
main_L17:
mov rax, 0
push rax
mov rax, rbp
mov rdi, 56
sub rax, rdi
push rax
mov rax, read
push rax
mov rax, rbp
mov rdi, 40
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 64
sub rax, rdi
mov rax, [rax]
push rax
mov rax, 8192
push rax
pop rdx
pop rsi
pop rdi
pop rax
call rax
pop rdi
mov [rdi], rax
pop rdi
xor rdx, rdx
cmp rax, rdi
setg dl
mov rax, rdx
test rax, rax
jnz main_L16
mov rax, close
push rax
mov rax, rbp
mov rdi, 40
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
pop rax
call rax
mov rax, close
push rax
mov rax, rbp
mov rdi, 48
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
pop rax
call rax
mov rax, 0
mov rsp, rbp
pop rbp
ret
mov rsp, rbp
pop rbp
ret
