; this code was generated by a tool.
bits 64

dir_equal_string:
push rbp
mov rbp, rsp
push rdi
push rsi
xor rax, rax
jmp dir_equal_string_L1
dir_equal_string_L0:
mov rax, 0
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
xor rax, rax
mov al, [rdi]
pop rdi
xor rdx, rdx
cmp rax, rdi
sete dl
mov rax, rdx
test rax, rax
jz dir_equal_string_L2
mov rax, 1
mov rsp, rbp
pop rbp
ret
jmp dir_equal_string_L3
dir_equal_string_L2:
dir_equal_string_L3:
mov rax, rbp
mov rdi, 8
sub rax, rdi
push rax
mov rax, 1
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
mov [rdi], rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
push rax
mov rax, 1
push rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
mov [rdi], rax
dir_equal_string_L1:
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
xor rax, rax
mov al, [rdi]
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
xor rax, rax
mov al, [rdi]
pop rdi
xor rdx, rdx
cmp rax, rdi
sete dl
mov rax, rdx
test rax, rax
jnz dir_equal_string_L0
mov rax, 0
mov rsp, rbp
pop rbp
ret
mov rsp, rbp
pop rbp
ret
dir_puts:
push rbp
mov rbp, rsp
push rdi
xor rax, rax
push rax
jmp dir_puts_L5
dir_puts_L4:
mov rax, putch
push rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
pop rax
call rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
push rax
mov rax, 1
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
mov [rdi], rax
dir_puts_L5:
mov rax, rbp
mov rdi, 16
sub rax, rdi
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
xor rax, rax
mov al, [rdi]
pop rdi
mov [rdi], rax
test rax, rax
jnz dir_puts_L4
mov rsp, rbp
pop rbp
ret
dir_div:
push rbp
mov rbp, rsp
push rdi
push rsi
xor rax, rax
push rax
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
pop rdi
mov [rdi], rax
mov rax, rbp
mov rdi, 32
sub rax, rdi
push rax
mov rax, 0
pop rdi
mov [rdi], rax
jmp dir_div_L7
dir_div_L6:
mov rax, rbp
mov rdi, 24
sub rax, rdi
push rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
pop rdi
sub rax, rdi
pop rdi
mov [rdi], rax
mov rax, rbp
mov rdi, 32
sub rax, rdi
push rax
mov rax, 1
push rax
mov rax, rbp
mov rdi, 32
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
mov [rdi], rax
dir_div_L7:
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
pop rdi
xor rdx, rdx
cmp rax, rdi
setge dl
mov rax, rdx
test rax, rax
jnz dir_div_L6
mov rax, rbp
mov rdi, 32
sub rax, rdi
mov rax, [rax]
mov rsp, rbp
pop rbp
ret
mov rsp, rbp
pop rbp
ret
dir_putn:
push rbp
mov rbp, rsp
push rdi
xor rax, rax
push rax
push rax
push rax
mov rax, 0
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
pop rdi
xor rdx, rdx
cmp rax, rdi
sete dl
mov rax, rdx
test rax, rax
jz dir_putn_L8
mov rax, dir_puts
push rax
jmp dir_putn_L11
dir_putn_L10:
db "0"
db 0
dir_putn_L11:
mov rax, dir_putn_L10
push rax
pop rdi
pop rax
call rax
mov rax, 0
mov rsp, rbp
pop rbp
ret
jmp dir_putn_L9
dir_putn_L8:
dir_putn_L9:
mov rax, rbp
mov rdi, 32
sub rax, rdi
push rax
mov rax, 1
pop rdi
mov [rdi], rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
push rax
mov rax, 1000000
pop rdi
mov [rdi], rax
jmp dir_putn_L13
dir_putn_L12:
mov rax, rbp
mov rdi, 16
sub rax, rdi
push rax
mov rax, dir_div
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
push rax
pop rsi
pop rdi
pop rax
call rax
pop rdi
mov [rdi], rax
mov rax, 0
push rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
pop rdi
xor rdx, rdx
cmp rax, rdi
setne dl
mov rax, rdx
test rax, rax
jz dir_putn_L14
mov rax, rbp
mov rdi, 32
sub rax, rdi
push rax
mov rax, 0
pop rdi
mov [rdi], rax
jmp dir_putn_L15
dir_putn_L14:
dir_putn_L15:
mov rax, 0
push rax
mov rax, rbp
mov rdi, 32
sub rax, rdi
mov rax, [rax]
pop rdi
xor rdx, rdx
cmp rax, rdi
sete dl
mov rax, rdx
test rax, rax
jz dir_putn_L16
mov rax, putch
push rax
jmp dir_putn_L19
dir_putn_L18:
db "0"
db 0
dir_putn_L19:
mov rax, dir_putn_L18
push rax
pop rdi
xor rax, rax
mov al, [rdi]
push rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
push rax
pop rdi
pop rax
call rax
jmp dir_putn_L17
dir_putn_L16:
dir_putn_L17:
mov rax, rbp
mov rdi, 8
sub rax, rdi
push rax
mov rax, dir_mod
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
push rax
pop rsi
pop rdi
pop rax
call rax
pop rdi
mov [rdi], rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
push rax
mov rax, dir_div
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
push rax
mov rax, 10
push rax
pop rsi
pop rdi
pop rax
call rax
pop rdi
mov [rdi], rax
dir_putn_L13:
mov rax, 0
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
pop rdi
xor rdx, rdx
cmp rax, rdi
setg dl
mov rax, rdx
test rax, rax
jnz dir_putn_L12
mov rsp, rbp
pop rbp
ret
dir_align:
push rbp
mov rbp, rsp
push rdi
xor rax, rax
jmp dir_align_L21
dir_align_L20:
mov rax, rbp
mov rdi, 8
sub rax, rdi
push rax
mov rax, 1
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
pop rdi
sub rax, rdi
pop rdi
mov [rdi], rax
mov rax, putch
push rax
mov rax, 32
push rax
pop rdi
pop rax
call rax
dir_align_L21:
mov rax, 0
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
pop rdi
xor rdx, rdx
cmp rax, rdi
setg dl
mov rax, rdx
test rax, rax
jnz dir_align_L20
mov rsp, rbp
pop rbp
ret
dir_strlen:
push rbp
mov rbp, rsp
push rdi
xor rax, rax
push rax
jmp dir_strlen_L23
dir_strlen_L22:
mov rax, rbp
mov rdi, 16
sub rax, rdi
push rax
mov rax, 1
push rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
mov [rdi], rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
push rax
mov rax, 1
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
mov [rdi], rax
dir_strlen_L23:
mov rax, 0
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
xor rax, rax
mov al, [rdi]
pop rdi
xor rdx, rdx
cmp rax, rdi
setne dl
mov rax, rdx
test rax, rax
jnz dir_strlen_L22
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
mov rsp, rbp
pop rbp
ret
mov rsp, rbp
pop rbp
ret
dir_mod:
push rbp
mov rbp, rsp
push rdi
push rsi
xor rax, rax
push rax
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
pop rdi
mov [rdi], rax
mov rax, rbp
mov rdi, 32
sub rax, rdi
push rax
mov rax, 0
pop rdi
mov [rdi], rax
jmp dir_mod_L25
dir_mod_L24:
mov rax, rbp
mov rdi, 24
sub rax, rdi
push rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
pop rdi
sub rax, rdi
pop rdi
mov [rdi], rax
mov rax, rbp
mov rdi, 32
sub rax, rdi
push rax
mov rax, 1
push rax
mov rax, rbp
mov rdi, 32
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
mov [rdi], rax
dir_mod_L25:
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
pop rdi
xor rdx, rdx
cmp rax, rdi
setge dl
mov rax, rdx
test rax, rax
jnz dir_mod_L24
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
mov rsp, rbp
pop rbp
ret
mov rsp, rbp
pop rbp
ret
main:
push rbp
mov rbp, rsp
xor rax, rax
push rax
push rax
push rax
push rax
push rax
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
push rax
mov rax, brk
push rax
mov rax, 1
neg rax
push rax
pop rdi
pop rax
call rax
pop rdi
mov [rdi], rax
mov rax, brk
push rax
mov rax, 65536
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
push rax
pop rdi
pop rax
call rax
mov rax, getcwd
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
push rax
mov rax, 65536
push rax
pop rsi
pop rdi
pop rax
call rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
push rax
mov rax, open
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
push rax
mov rax, 0
push rax
pop rsi
pop rdi
pop rax
call rax
pop rdi
mov [rdi], rax
mov rax, rbp
mov rdi, 32
sub rax, rdi
push rax
mov rax, getdents64
push rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
push rax
mov rax, 65536
push rax
pop rdx
pop rsi
pop rdi
pop rax
call rax
pop rdi
mov [rdi], rax
mov rax, close
push rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
pop rax
call rax
mov rax, dir_puts
push rax
jmp main_L27
main_L26:
db "[.]"
db 0
main_L27:
mov rax, main_L26
push rax
pop rdi
pop rax
call rax
mov rax, putch
push rax
mov rax, 10
push rax
pop rdi
pop rax
call rax
mov rax, dir_puts
push rax
jmp main_L29
main_L28:
db "[..]"
db 0
main_L29:
mov rax, main_L28
push rax
pop rdi
pop rax
call rax
mov rax, putch
push rax
mov rax, 10
push rax
pop rdi
pop rax
call rax
jmp main_L31
main_L30:
mov rax, rbp
mov rdi, 40
sub rax, rdi
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
mov [rdi], rax
mov rax, rbp
mov rdi, 48
sub rax, rdi
push rax
mov rax, 18
push rax
mov rax, rbp
mov rdi, 40
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
push rax
pop rdi
xor rax, rax
mov al, [rdi]
pop rdi
mov [rdi], rax
mov rax, 4
push rax
mov rax, rbp
mov rdi, 48
sub rax, rdi
mov rax, [rax]
pop rdi
xor rdx, rdx
cmp rax, rdi
sete dl
mov rax, rdx
test rax, rax
jz main_L32
mov rax, 0
push rax
mov rax, dir_equal_string
push rax
mov rax, 19
push rax
mov rax, rbp
mov rdi, 40
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
push rax
jmp main_L37
main_L36:
db "."
db 0
main_L37:
mov rax, main_L36
push rax
pop rsi
pop rdi
pop rax
call rax
push rax
mov rax, dir_equal_string
push rax
mov rax, 19
push rax
mov rax, rbp
mov rdi, 40
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
push rax
jmp main_L39
main_L38:
db ".."
db 0
main_L39:
mov rax, main_L38
push rax
pop rsi
pop rdi
pop rax
call rax
pop rdi
or rax, rdi
pop rdi
xor rdx, rdx
cmp rax, rdi
sete dl
mov rax, rdx
test rax, rax
jz main_L34
mov rax, dir_puts
push rax
jmp main_L41
main_L40:
db "["
db 0
main_L41:
mov rax, main_L40
push rax
pop rdi
pop rax
call rax
mov rax, dir_puts
push rax
mov rax, 19
push rax
mov rax, rbp
mov rdi, 40
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
push rax
pop rdi
pop rax
call rax
mov rax, dir_puts
push rax
jmp main_L43
main_L42:
db "] "
db 0
main_L43:
mov rax, main_L42
push rax
pop rdi
pop rax
call rax
mov rax, putch
push rax
mov rax, 10
push rax
pop rdi
pop rax
call rax
jmp main_L35
main_L34:
main_L35:
jmp main_L33
main_L32:
main_L33:
mov rax, rbp
mov rdi, 24
sub rax, rdi
push rax
mov rax, 65535
push rax
mov rax, 16
push rax
mov rax, rbp
mov rdi, 40
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
mov rax, [rax]
pop rdi
and rax, rdi
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
mov [rdi], rax
main_L31:
mov rax, rbp
mov rdi, 32
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
pop rdi
xor rdx, rdx
cmp rax, rdi
setl dl
mov rax, rdx
test rax, rax
jnz main_L30
mov rax, rbp
mov rdi, 24
sub rax, rdi
push rax
mov rax, 0
pop rdi
mov [rdi], rax
jmp main_L45
main_L44:
mov rax, rbp
mov rdi, 40
sub rax, rdi
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
mov [rdi], rax
mov rax, rbp
mov rdi, 48
sub rax, rdi
push rax
mov rax, 18
push rax
mov rax, rbp
mov rdi, 40
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
push rax
pop rdi
xor rax, rax
mov al, [rdi]
pop rdi
mov [rdi], rax
mov rax, 4
push rax
mov rax, rbp
mov rdi, 48
sub rax, rdi
mov rax, [rax]
pop rdi
xor rdx, rdx
cmp rax, rdi
setne dl
mov rax, rdx
test rax, rax
jz main_L46
mov rax, dir_puts
push rax
mov rax, 19
push rax
mov rax, rbp
mov rdi, 40
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
push rax
pop rdi
pop rax
call rax
mov rax, dir_align
push rax
mov rax, dir_strlen
push rax
mov rax, 19
push rax
mov rax, rbp
mov rdi, 40
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
push rax
pop rdi
pop rax
call rax
push rax
mov rax, 20
pop rdi
sub rax, rdi
push rax
pop rdi
pop rax
call rax
mov rax, dir_putn
push rax
mov rax, rbp
mov rdi, 40
sub rax, rdi
mov rax, [rax]
mov rax, [rax]
push rax
pop rdi
pop rax
call rax
mov rax, dir_puts
push rax
jmp main_L49
main_L48:
db " bytes"
db 0
main_L49:
mov rax, main_L48
push rax
pop rdi
pop rax
call rax
mov rax, putch
push rax
mov rax, 10
push rax
pop rdi
pop rax
call rax
jmp main_L47
main_L46:
main_L47:
mov rax, rbp
mov rdi, 24
sub rax, rdi
push rax
mov rax, 65535
push rax
mov rax, 16
push rax
mov rax, rbp
mov rdi, 40
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
mov rax, [rax]
pop rdi
and rax, rdi
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
mov [rdi], rax
main_L45:
mov rax, rbp
mov rdi, 32
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
pop rdi
xor rdx, rdx
cmp rax, rdi
setl dl
mov rax, rdx
test rax, rax
jnz main_L44
mov rsp, rbp
pop rbp
ret
