; this code was generated by a tool.
bits 64

puts:
push rbp
mov rbp, rsp
push rdi
xor rax, rax
push rax
jmp puts_L1
puts_L0:
mov rax, putch
push rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
pop rax
call rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
push rax
mov rax, 1
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
mov [rdi], rax
puts_L1:
mov rax, rbp
mov rdi, 16
sub rax, rdi
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
xor rax, rax
mov al, [rdi]
pop rdi
mov [rdi], rax
test rax, rax
jnz puts_L0
mov rax, 0
mov rsp, rbp
pop rbp
ret
mov rsp, rbp
pop rbp
ret
nextarg:
push rbp
mov rbp, rsp
push rdi
xor rax, rax
push rax
jmp nextarg_L3
nextarg_L2:
mov rax, rbp
mov rdi, 8
sub rax, rdi
push rax
mov rax, 1
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
mov [rdi], rax
nextarg_L3:
mov rax, rbp
mov rdi, 16
sub rax, rdi
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
xor rax, rax
mov al, [rdi]
pop rdi
mov [rdi], rax
test rax, rax
jnz nextarg_L2
mov rax, 1
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
mov rsp, rbp
pop rbp
ret
mov rsp, rbp
pop rbp
ret
main:
push rbp
mov rbp, rsp
push rdi
push rsi
xor rax, rax
push rax
push rax
jmp main_L5
main_L4:
mov rax, rbp
mov rdi, 16
sub rax, rdi
push rax
mov rax, nextarg
push rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
pop rax
call rax
pop rdi
mov [rdi], rax
mov rax, puts
push rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
pop rax
call rax
mov rax, putch
push rax
mov rax, 32
push rax
pop rdi
pop rax
call rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
push rax
mov rax, 1
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
pop rdi
sub rax, rdi
pop rdi
mov [rdi], rax
main_L5:
mov rax, 1
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
pop rdi
xor rdx, rdx
cmp rax, rdi
setg dl
mov rax, rdx
test rax, rax
jnz main_L4
mov rax, putch
push rax
mov rax, 10
push rax
pop rdi
pop rax
call rax
mov rax, putch
push rax
mov rax, 0
push rax
pop rdi
pop rax
call rax
mov rax, 0
mov rsp, rbp
pop rbp
ret
mov rsp, rbp
pop rbp
ret
