; this code was generated by a tool.
bits 64

str_is_equal:
push rbp
mov rbp, rsp
push rdi
push rsi
xor rax, rax
jmp str_is_equal_L1
str_is_equal_L0:
mov rax, rbp
mov rdi, 8
sub rax, rdi
push rax
mov rax, 1
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
mov [rdi], rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
push rax
mov rax, 1
push rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
mov [rdi], rax
str_is_equal_L1:
mov rax, 0
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
xor rax, rax
mov al, [rdi]
pop rdi
xor rdx, rdx
cmp rax, rdi
setne dl
mov rax, rdx
push rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
xor rax, rax
mov al, [rdi]
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
xor rax, rax
mov al, [rdi]
pop rdi
xor rdx, rdx
cmp rax, rdi
sete dl
mov rax, rdx
pop rdi
and rax, rdi
test rax, rax
jnz str_is_equal_L0
mov rax, 0
push rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
xor rax, rax
mov al, [rdi]
pop rdi
xor rdx, rdx
cmp rax, rdi
sete dl
mov rax, rdx
push rax
mov rax, 0
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
xor rax, rax
mov al, [rdi]
pop rdi
xor rdx, rdx
cmp rax, rdi
sete dl
mov rax, rdx
pop rdi
and rax, rdi
mov rsp, rbp
pop rbp
ret
mov rsp, rbp
pop rbp
ret
strlen:
push rbp
mov rbp, rsp
push rdi
xor rax, rax
push rax
jmp strlen_L3
strlen_L2:
mov rax, rbp
mov rdi, 16
sub rax, rdi
push rax
mov rax, 1
push rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
mov [rdi], rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
push rax
mov rax, 1
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
mov [rdi], rax
strlen_L3:
mov rax, 0
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
xor rax, rax
mov al, [rdi]
pop rdi
xor rdx, rdx
cmp rax, rdi
setne dl
mov rax, rdx
test rax, rax
jnz strlen_L2
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
mov rsp, rbp
pop rbp
ret
mov rsp, rbp
pop rbp
ret
puts:
push rbp
mov rbp, rsp
push rdi
xor rax, rax
jmp puts_L5
puts_L4:
mov rax, putch
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
xor rax, rax
mov al, [rdi]
push rax
pop rdi
pop rax
call rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
push rax
mov rax, 1
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
mov [rdi], rax
puts_L5:
mov rax, 0
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
xor rax, rax
mov al, [rdi]
pop rdi
xor rdx, rdx
cmp rax, rdi
setne dl
mov rax, rdx
test rax, rax
jnz puts_L4
mov rsp, rbp
pop rbp
ret
nextArg:
push rbp
mov rbp, rsp
push rdi
xor rax, rax
push rax
jmp nextArg_L7
nextArg_L6:
mov rax, rbp
mov rdi, 8
sub rax, rdi
push rax
mov rax, 1
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
mov [rdi], rax
nextArg_L7:
mov rax, rbp
mov rdi, 16
sub rax, rdi
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
xor rax, rax
mov al, [rdi]
pop rdi
mov [rdi], rax
test rax, rax
jnz nextArg_L6
mov rax, 1
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
mov rsp, rbp
pop rbp
ret
mov rsp, rbp
pop rbp
ret
jar_unpack:
push rbp
mov rbp, rsp
push rdi
push rsi
push rdx
xor rax, rax
push rax
push rax
push rax
push rax
push rax
push rax
mov rax, rbp
mov rdi, 32
sub rax, rdi
push rax
mov rax, brk
push rax
mov rax, 1
neg rax
push rax
pop rdi
pop rax
call rax
pop rdi
mov [rdi], rax
mov rax, brk
push rax
mov rax, 65536
push rax
mov rax, rbp
mov rdi, 32
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
push rax
pop rdi
pop rax
call rax
jmp jar_unpack_L9
jar_unpack_L8:
mov rax, rbp
mov rdi, 48
sub rax, rdi
push rax
mov rax, rbp
mov rdi, 32
sub rax, rdi
mov rax, [rax]
pop rdi
mov [rdi], rax
mov rax, rbp
mov rdi, 56
sub rax, rdi
push rax
mov rax, 0
pop rdi
mov [rdi], rax
jmp jar_unpack_L11
jar_unpack_L10:
mov rax, 0
push rax
mov rax, read
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 48
sub rax, rdi
mov rax, [rax]
push rax
mov rax, 1
push rax
pop rdx
pop rsi
pop rdi
pop rax
call rax
pop rdi
xor rdx, rdx
cmp rax, rdi
setle dl
mov rax, rdx
test rax, rax
jz jar_unpack_L12
mov rax, 0
mov rsp, rbp
pop rbp
ret
jmp jar_unpack_L13
jar_unpack_L12:
jar_unpack_L13:
mov rax, rbp
mov rdi, 56
sub rax, rdi
push rax
mov rax, 0
push rax
mov rax, rbp
mov rdi, 48
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
xor rax, rax
mov al, [rdi]
pop rdi
xor rdx, rdx
cmp rax, rdi
sete dl
mov rax, rdx
pop rdi
mov [rdi], rax
mov rax, rbp
mov rdi, 48
sub rax, rdi
push rax
mov rax, 1
push rax
mov rax, rbp
mov rdi, 48
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
mov [rdi], rax
jar_unpack_L11:
mov rax, 0
push rax
mov rax, rbp
mov rdi, 56
sub rax, rdi
mov rax, [rax]
pop rdi
xor rdx, rdx
cmp rax, rdi
sete dl
mov rax, rdx
test rax, rax
jnz jar_unpack_L10
mov rax, 0
push rax
mov rax, strlen
push rax
mov rax, rbp
mov rdi, 32
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
pop rax
call rax
pop rdi
xor rdx, rdx
cmp rax, rdi
sete dl
mov rax, rdx
test rax, rax
jz jar_unpack_L14
mov rax, 0
mov rsp, rbp
pop rbp
ret
jmp jar_unpack_L15
jar_unpack_L14:
jar_unpack_L15:
mov rax, read
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
push rax
mov rax, 8
push rax
pop rdx
pop rsi
pop rdi
pop rax
call rax
jmp jar_unpack_L19
jar_unpack_L18:
db "/"
db 0
jar_unpack_L19:
mov rax, jar_unpack_L18
push rax
pop rdi
xor rax, rax
mov al, [rdi]
push rax
mov rax, 1
push rax
mov rax, strlen
push rax
mov rax, rbp
mov rdi, 32
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
pop rax
call rax
push rax
mov rax, rbp
mov rdi, 32
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
sub rax, rdi
push rax
pop rdi
xor rax, rax
mov al, [rdi]
pop rdi
xor rdx, rdx
cmp rax, rdi
sete dl
mov rax, rdx
test rax, rax
jz jar_unpack_L16
mov rax, mkdir
push rax
mov rax, rbp
mov rdi, 32
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
pop rax
call rax
jmp jar_unpack_L17
jar_unpack_L16:
mov rax, rbp
mov rdi, 72
sub rax, rdi
push rax
mov rax, creat
push rax
mov rax, rbp
mov rdi, 32
sub rax, rdi
mov rax, [rax]
push rax
mov rax, 0
push rax
pop rsi
pop rdi
pop rax
call rax
pop rdi
mov [rdi], rax
mov rax, read
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
mov rax, [rax]
push rax
pop rdx
pop rsi
pop rdi
pop rax
call rax
mov rax, write
push rax
mov rax, rbp
mov rdi, 72
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
mov rax, [rax]
push rax
pop rdx
pop rsi
pop rdi
pop rax
call rax
mov rax, close
push rax
mov rax, rbp
mov rdi, 72
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
pop rax
call rax
jar_unpack_L17:
jar_unpack_L9:
mov rax, 1
test rax, rax
jnz jar_unpack_L8
mov rsp, rbp
pop rbp
ret
jar_pack:
push rbp
mov rbp, rsp
push rdi
push rsi
push rdx
push rcx
push r8
xor rax, rax
push rax
push rax
push rax
push rax
push rax
push rax
push rax
push rax
push rax
push rax
push rax
push rax
mov rax, rbp
mov rdi, 48
sub rax, rdi
push rax
mov rax, brk
push rax
mov rax, 1
neg rax
push rax
pop rdi
pop rax
call rax
pop rdi
mov [rdi], rax
mov rax, brk
push rax
mov rax, 65536
push rax
mov rax, rbp
mov rdi, 48
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
push rax
pop rdi
pop rax
call rax
mov rax, rbp
mov rdi, 128
sub rax, rdi
push rax
mov rax, brk
push rax
mov rax, 1
neg rax
push rax
pop rdi
pop rax
call rax
pop rdi
mov [rdi], rax
mov rax, brk
push rax
mov rax, 65536
push rax
mov rax, rbp
mov rdi, 128
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
push rax
pop rdi
pop rax
call rax
jmp jar_pack_L21
jar_pack_L20:
mov rax, rbp
mov rdi, 56
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 48
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
push rax
mov rax, rbp
mov rdi, 56
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 32
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
push rax
pop rdi
xor rax, rax
mov al, [rdi]
pop rdi
mov [rdi], al
mov rax, rbp
mov rdi, 56
sub rax, rdi
push rax
mov rax, 1
push rax
mov rax, rbp
mov rdi, 56
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
mov [rdi], rax
jar_pack_L21:
mov rax, strlen
push rax
mov rax, rbp
mov rdi, 32
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
pop rax
call rax
push rax
mov rax, rbp
mov rdi, 56
sub rax, rdi
mov rax, [rax]
pop rdi
xor rdx, rdx
cmp rax, rdi
setl dl
mov rax, rdx
test rax, rax
jnz jar_pack_L20
mov rax, rbp
mov rdi, 64
sub rax, rdi
push rax
mov rax, strlen
push rax
mov rax, rbp
mov rdi, 48
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
pop rax
call rax
pop rdi
mov [rdi], rax
mov rax, rbp
mov rdi, 72
sub rax, rdi
push rax
mov rax, open
push rax
mov rax, rbp
mov rdi, 48
sub rax, rdi
mov rax, [rax]
push rax
mov rax, 0
push rax
pop rsi
pop rdi
pop rax
call rax
pop rdi
mov [rdi], rax
mov rax, rbp
mov rdi, 104
sub rax, rdi
push rax
mov rax, getdents64
push rax
mov rax, rbp
mov rdi, 72
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 128
sub rax, rdi
mov rax, [rax]
push rax
mov rax, 65536
push rax
pop rdx
pop rsi
pop rdi
pop rax
call rax
pop rdi
mov [rdi], rax
mov rax, close
push rax
mov rax, rbp
mov rdi, 72
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
pop rax
call rax
jmp jar_pack_L23
jar_pack_L22:
mov rax, rbp
mov rdi, 112
sub rax, rdi
push rax
mov rax, rbp
mov rdi, 96
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 128
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
mov [rdi], rax
mov rax, rbp
mov rdi, 120
sub rax, rdi
push rax
mov rax, 18
push rax
mov rax, rbp
mov rdi, 112
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
push rax
pop rdi
xor rax, rax
mov al, [rdi]
pop rdi
mov [rdi], rax
mov rax, rbp
mov rdi, 80
sub rax, rdi
push rax
mov rax, 19
push rax
mov rax, rbp
mov rdi, 112
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
mov [rdi], rax
mov rax, rbp
mov rdi, 56
sub rax, rdi
push rax
mov rax, strlen
push rax
mov rax, rbp
mov rdi, 80
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
pop rax
call rax
pop rdi
mov [rdi], rax
jmp jar_pack_L25
jar_pack_L24:
mov rax, rbp
mov rdi, 56
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 64
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 48
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
add rax, rdi
push rax
mov rax, rbp
mov rdi, 56
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 80
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
push rax
pop rdi
xor rax, rax
mov al, [rdi]
pop rdi
mov [rdi], al
mov rax, rbp
mov rdi, 56
sub rax, rdi
push rax
mov rax, 1
push rax
mov rax, rbp
mov rdi, 56
sub rax, rdi
mov rax, [rax]
pop rdi
sub rax, rdi
pop rdi
mov [rdi], rax
jar_pack_L25:
mov rax, 0
push rax
mov rax, rbp
mov rdi, 56
sub rax, rdi
mov rax, [rax]
pop rdi
xor rdx, rdx
cmp rax, rdi
setge dl
mov rax, rdx
test rax, rax
jnz jar_pack_L24
mov rax, 0
push rax
mov rax, str_is_equal
push rax
mov rax, rbp
mov rdi, 40
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 80
sub rax, rdi
mov rax, [rax]
push rax
pop rsi
pop rdi
pop rax
call rax
pop rdi
xor rdx, rdx
cmp rax, rdi
sete dl
mov rax, rdx
test rax, rax
jz jar_pack_L26
mov rax, 4
push rax
mov rax, rbp
mov rdi, 120
sub rax, rdi
mov rax, [rax]
pop rdi
xor rdx, rdx
cmp rax, rdi
setne dl
mov rax, rdx
test rax, rax
jz jar_pack_L28
mov rax, rbp
mov rdi, 72
sub rax, rdi
push rax
mov rax, open
push rax
mov rax, rbp
mov rdi, 48
sub rax, rdi
mov rax, [rax]
push rax
mov rax, 0
push rax
pop rsi
pop rdi
pop rax
call rax
pop rdi
mov [rdi], rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
push rax
mov rax, 0
pop rdi
mov [rdi], rax
mov rax, rbp
mov rdi, 136
sub rax, rdi
push rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
pop rdi
mov [rdi], rax
jmp jar_pack_L31
jar_pack_L30:
mov rax, rbp
mov rdi, 136
sub rax, rdi
push rax
mov rax, 1
push rax
mov rax, rbp
mov rdi, 136
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
mov [rdi], rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
push rax
mov rax, 1
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
mov [rdi], rax
jar_pack_L31:
mov rax, 0
push rax
mov rax, read
push rax
mov rax, rbp
mov rdi, 72
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 136
sub rax, rdi
mov rax, [rax]
push rax
mov rax, 1
push rax
pop rdx
pop rsi
pop rdi
pop rax
call rax
pop rdi
xor rdx, rdx
cmp rax, rdi
setg dl
mov rax, rdx
test rax, rax
jnz jar_pack_L30
mov rax, close
push rax
mov rax, rbp
mov rdi, 72
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
pop rax
call rax
mov rax, write
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 48
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 64
sub rax, rdi
mov rax, [rax]
push rax
pop rdx
pop rsi
pop rdi
pop rax
call rax
mov rax, write
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 80
sub rax, rdi
mov rax, [rax]
push rax
mov rax, 1
push rax
mov rax, strlen
push rax
mov rax, rbp
mov rdi, 80
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
pop rax
call rax
pop rdi
add rax, rdi
push rax
pop rdx
pop rsi
pop rdi
pop rax
call rax
mov rax, write
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
push rax
mov rax, 8
push rax
pop rdx
pop rsi
pop rdi
pop rax
call rax
mov rax, write
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
mov rax, [rax]
push rax
pop rdx
pop rsi
pop rdi
pop rax
call rax
jmp jar_pack_L29
jar_pack_L28:
jmp jar_pack_L35
jar_pack_L34:
db "."
db 0
jar_pack_L35:
mov rax, jar_pack_L34
push rax
pop rdi
xor rax, rax
mov al, [rdi]
push rax
mov rax, rbp
mov rdi, 80
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
xor rax, rax
mov al, [rdi]
pop rdi
xor rdx, rdx
cmp rax, rdi
setne dl
mov rax, rdx
test rax, rax
jz jar_pack_L32
mov rax, rbp
mov rdi, 56
sub rax, rdi
push rax
mov rax, strlen
push rax
mov rax, rbp
mov rdi, 48
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
pop rax
call rax
pop rdi
mov [rdi], rax
mov rax, rbp
mov rdi, 56
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 48
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
push rax
jmp jar_pack_L37
jar_pack_L36:
db "/"
db 0
jar_pack_L37:
mov rax, jar_pack_L36
push rax
pop rdi
xor rax, rax
mov al, [rdi]
pop rdi
mov [rdi], al
mov rax, 1
push rax
mov rax, rbp
mov rdi, 56
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 48
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
add rax, rdi
push rax
mov rax, 0
pop rdi
mov [rdi], al
mov rax, write
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 48
sub rax, rdi
mov rax, [rax]
push rax
mov rax, 1
push rax
mov rax, strlen
push rax
mov rax, rbp
mov rdi, 48
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
pop rax
call rax
pop rdi
add rax, rdi
push rax
pop rdx
pop rsi
pop rdi
pop rax
call rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
push rax
mov rax, 0
pop rdi
mov [rdi], rax
mov rax, write
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
push rax
mov rax, 8
push rax
pop rdx
pop rsi
pop rdi
pop rax
call rax
mov rax, jar_pack
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 48
sub rax, rdi
mov rax, [rax]
push rax
jmp jar_pack_L39
jar_pack_L38:
db ""
db 0
jar_pack_L39:
mov rax, jar_pack_L38
push rax
pop r8
pop rcx
pop rdx
pop rsi
pop rdi
pop rax
call rax
jmp jar_pack_L33
jar_pack_L32:
jar_pack_L33:
jar_pack_L29:
jmp jar_pack_L27
jar_pack_L26:
jar_pack_L27:
mov rax, rbp
mov rdi, 96
sub rax, rdi
push rax
mov rax, 65535
push rax
mov rax, 16
push rax
mov rax, rbp
mov rdi, 112
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
mov rax, [rax]
pop rdi
and rax, rdi
push rax
mov rax, rbp
mov rdi, 96
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
mov [rdi], rax
jar_pack_L23:
mov rax, rbp
mov rdi, 104
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 96
sub rax, rdi
mov rax, [rax]
pop rdi
xor rdx, rdx
cmp rax, rdi
setl dl
mov rax, rdx
test rax, rax
jnz jar_pack_L22
mov rsp, rbp
pop rbp
ret
main:
push rbp
mov rbp, rsp
push rdi
push rsi
xor rax, rax
push rax
push rax
push rax
push rax
mov rax, 3
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
pop rdi
xor rdx, rdx
cmp rax, rdi
setne dl
mov rax, rdx
test rax, rax
jz main_L40
mov rax, puts
push rax
jmp main_L43
main_L42:
db "usage: jar c|x file"
db 0
main_L43:
mov rax, main_L42
push rax
pop rdi
pop rax
call rax
mov rax, putch
push rax
mov rax, 10
push rax
pop rdi
pop rax
call rax
mov rax, 0
mov rsp, rbp
pop rbp
ret
jmp main_L41
main_L40:
main_L41:
mov rax, rbp
mov rdi, 24
sub rax, rdi
push rax
mov rax, brk
push rax
mov rax, 1
neg rax
push rax
pop rdi
pop rax
call rax
pop rdi
mov [rdi], rax
mov rax, brk
push rax
mov rax, 20
push rax
mov rax, 1
pop rdi
mov rcx, rdi
shl rax, cl
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
push rax
pop rdi
pop rax
call rax
mov rax, rbp
mov rdi, 32
sub rax, rdi
push rax
mov rax, brk
push rax
mov rax, 1
neg rax
push rax
pop rdi
pop rax
call rax
pop rdi
mov [rdi], rax
mov rax, brk
push rax
mov rax, 8
push rax
mov rax, rbp
mov rdi, 32
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
push rax
pop rdi
pop rax
call rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
push rax
mov rax, nextArg
push rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
pop rax
call rax
pop rdi
mov [rdi], rax
mov rax, rbp
mov rdi, 48
sub rax, rdi
push rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
xor rax, rax
mov al, [rdi]
pop rdi
mov [rdi], rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
push rax
mov rax, nextArg
push rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
pop rax
call rax
pop rdi
mov [rdi], rax
jmp main_L47
main_L46:
db "c"
db 0
main_L47:
mov rax, main_L46
push rax
pop rdi
xor rax, rax
mov al, [rdi]
push rax
mov rax, rbp
mov rdi, 48
sub rax, rdi
mov rax, [rax]
pop rdi
xor rdx, rdx
cmp rax, rdi
sete dl
mov rax, rdx
test rax, rax
jz main_L44
mov rax, rbp
mov rdi, 40
sub rax, rdi
push rax
mov rax, creat
push rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
pop rax
call rax
pop rdi
mov [rdi], rax
mov rax, jar_pack
push rax
mov rax, rbp
mov rdi, 40
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 32
sub rax, rdi
mov rax, [rax]
push rax
jmp main_L49
main_L48:
db "./"
db 0
main_L49:
mov rax, main_L48
push rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
push rax
pop r8
pop rcx
pop rdx
pop rsi
pop rdi
pop rax
call rax
mov rax, fputch
push rax
mov rax, rbp
mov rdi, 40
sub rax, rdi
mov rax, [rax]
push rax
mov rax, 0
push rax
pop rsi
pop rdi
pop rax
call rax
mov rax, close
push rax
mov rax, rbp
mov rdi, 40
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
pop rax
call rax
jmp main_L45
main_L44:
jmp main_L53
main_L52:
db "x"
db 0
main_L53:
mov rax, main_L52
push rax
pop rdi
xor rax, rax
mov al, [rdi]
push rax
mov rax, rbp
mov rdi, 48
sub rax, rdi
mov rax, [rax]
pop rdi
xor rdx, rdx
cmp rax, rdi
sete dl
mov rax, rdx
test rax, rax
jz main_L50
mov rax, rbp
mov rdi, 40
sub rax, rdi
push rax
mov rax, open
push rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
push rax
mov rax, 0
push rax
pop rsi
pop rdi
pop rax
call rax
pop rdi
mov [rdi], rax
mov rax, jar_unpack
push rax
mov rax, rbp
mov rdi, 40
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 32
sub rax, rdi
mov rax, [rax]
push rax
pop rdx
pop rsi
pop rdi
pop rax
call rax
jmp main_L51
main_L50:
mov rax, puts
push rax
jmp main_L55
main_L54:
db "unknown mode"
db 0
main_L55:
mov rax, main_L54
push rax
pop rdi
pop rax
call rax
mov rax, putch
push rax
mov rax, 10
push rax
pop rdi
pop rax
call rax
main_L51:
main_L45:
mov rsp, rbp
pop rbp
ret
