; this code was generated by a tool.
bits 64

malloc:
push rbp
mov rbp, rsp
push rdi
xor rax, rax
push rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
push rax
mov rax, brk
push rax
mov rax, 1
neg rax
push rax
pop rdi
pop rax
call rax
pop rdi
mov [rdi], rax
mov rax, brk
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
push rax
pop rdi
pop rax
call rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
mov rsp, rbp
pop rbp
ret
mov rsp, rbp
pop rbp
ret
puts:
push rbp
mov rbp, rsp
push rdi
xor rax, rax
push rax
jmp puts_L1
puts_L0:
mov rax, putch
push rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
pop rax
call rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
push rax
mov rax, 1
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
mov [rdi], rax
puts_L1:
mov rax, rbp
mov rdi, 16
sub rax, rdi
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
xor rax, rax
mov al, [rdi]
pop rdi
mov [rdi], rax
test rax, rax
jnz puts_L0
mov rax, 0
mov rsp, rbp
pop rbp
ret
mov rsp, rbp
pop rbp
ret
nextarg:
push rbp
mov rbp, rsp
push rdi
xor rax, rax
push rax
jmp nextarg_L3
nextarg_L2:
mov rax, rbp
mov rdi, 8
sub rax, rdi
push rax
mov rax, 1
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
mov [rdi], rax
nextarg_L3:
mov rax, rbp
mov rdi, 16
sub rax, rdi
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
xor rax, rax
mov al, [rdi]
pop rdi
mov [rdi], rax
test rax, rax
jnz nextarg_L2
mov rax, 1
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
mov rsp, rbp
pop rbp
ret
mov rsp, rbp
pop rbp
ret
mod:
push rbp
mov rbp, rsp
push rdi
push rsi
xor rax, rax
push rax
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
pop rdi
mov [rdi], rax
mov rax, rbp
mov rdi, 32
sub rax, rdi
push rax
mov rax, 0
pop rdi
mov [rdi], rax
jmp mod_L5
mod_L4:
mov rax, rbp
mov rdi, 24
sub rax, rdi
push rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
pop rdi
sub rax, rdi
pop rdi
mov [rdi], rax
mov rax, rbp
mov rdi, 32
sub rax, rdi
push rax
mov rax, 1
push rax
mov rax, rbp
mov rdi, 32
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
mov [rdi], rax
mod_L5:
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
pop rdi
xor rdx, rdx
cmp rax, rdi
setge dl
mov rax, rdx
test rax, rax
jnz mod_L4
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
mov rsp, rbp
pop rbp
ret
mov rsp, rbp
pop rbp
ret
compress:
push rbp
mov rbp, rsp
push rdi
push rsi
xor rax, rax
push rax
push rax
push rax
push rax
push rax
push rax
push rax
push rax
push rax
push rax
push rax
push rax
push rax
push rax
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
push rax
mov rax, malloc
push rax
mov rax, 3
push rax
pop rdi
pop rax
call rax
pop rdi
mov [rdi], rax
mov rax, rbp
mov rdi, 80
sub rax, rdi
push rax
mov rax, malloc
push rax
mov rax, 20
push rax
mov rax, 1
pop rdi
mov rcx, rdi
shl rax, cl
push rax
pop rdi
pop rax
call rax
pop rdi
mov [rdi], rax
mov rax, rbp
mov rdi, 48
sub rax, rdi
push rax
mov rax, malloc
push rax
mov rax, 1024
push rax
pop rdi
pop rax
call rax
pop rdi
mov [rdi], rax
mov rax, rbp
mov rdi, 56
sub rax, rdi
push rax
mov rax, 0
pop rdi
mov [rdi], rax
mov rax, rbp
mov rdi, 88
sub rax, rdi
push rax
mov rax, 0
pop rdi
mov [rdi], rax
jmp compress_L7
compress_L6:
mov rax, rbp
mov rdi, 88
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 80
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
xor rax, rax
mov al, [rdi]
pop rdi
mov [rdi], al
mov rax, rbp
mov rdi, 88
sub rax, rdi
push rax
mov rax, 1
push rax
mov rax, rbp
mov rdi, 88
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
mov [rdi], rax
compress_L7:
mov rax, 0
push rax
mov rax, read
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
push rax
mov rax, 1
push rax
pop rdx
pop rsi
pop rdi
pop rax
call rax
pop rdi
xor rdx, rdx
cmp rax, rdi
setg dl
mov rax, rdx
test rax, rax
jnz compress_L6
mov rax, rbp
mov rdi, 96
sub rax, rdi
push rax
mov rax, 0
pop rdi
mov [rdi], rax
jmp compress_L9
compress_L8:
mov rax, rbp
mov rdi, 104
sub rax, rdi
push rax
mov rax, 0
pop rdi
mov [rdi], rax
mov rax, rbp
mov rdi, 128
sub rax, rdi
push rax
mov rax, 0
pop rdi
mov [rdi], rax
mov rax, rbp
mov rdi, 136
sub rax, rdi
push rax
mov rax, 0
pop rdi
mov [rdi], rax
jmp compress_L11
compress_L10:
mov rax, rbp
mov rdi, 112
sub rax, rdi
push rax
mov rax, 0
pop rdi
mov [rdi], rax
mov rax, rbp
mov rdi, 120
sub rax, rdi
push rax
mov rax, 0
pop rdi
mov [rdi], rax
jmp compress_L13
compress_L12:
mov rax, rbp
mov rdi, 32
sub rax, rdi
push rax
mov rax, rbp
mov rdi, 112
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 96
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 80
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
add rax, rdi
push rax
pop rdi
xor rax, rax
mov al, [rdi]
pop rdi
mov [rdi], rax
mov rax, rbp
mov rdi, 40
sub rax, rdi
push rax
mov rax, mod
push rax
mov rax, rbp
mov rdi, 112
sub rax, rdi
mov rax, [rax]
push rax
mov rax, 1
push rax
mov rax, rbp
mov rdi, 104
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
push rax
pop rsi
pop rdi
pop rax
call rax
push rax
mov rax, rbp
mov rdi, 104
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 48
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
sub rax, rdi
push rax
pop rdi
xor rax, rax
mov al, [rdi]
pop rdi
mov [rdi], rax
mov rax, rbp
mov rdi, 40
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 32
sub rax, rdi
mov rax, [rax]
pop rdi
xor rdx, rdx
cmp rax, rdi
sete dl
mov rax, rdx
test rax, rax
jz compress_L14
mov rax, rbp
mov rdi, 112
sub rax, rdi
push rax
mov rax, 1
push rax
mov rax, rbp
mov rdi, 112
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
mov [rdi], rax
jmp compress_L15
compress_L14:
mov rax, rbp
mov rdi, 120
sub rax, rdi
push rax
mov rax, 1
pop rdi
mov [rdi], rax
compress_L15:
compress_L13:
mov rax, 63
push rax
mov rax, rbp
mov rdi, 112
sub rax, rdi
mov rax, [rax]
pop rdi
xor rdx, rdx
cmp rax, rdi
setl dl
mov rax, rdx
push rax
mov rax, 0
push rax
mov rax, rbp
mov rdi, 120
sub rax, rdi
mov rax, [rax]
pop rdi
xor rdx, rdx
cmp rax, rdi
sete dl
mov rax, rdx
push rax
mov rax, rbp
mov rdi, 88
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 112
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 96
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
xor rdx, rdx
cmp rax, rdi
setl dl
mov rax, rdx
pop rdi
and rax, rdi
pop rdi
and rax, rdi
test rax, rax
jnz compress_L12
mov rax, rbp
mov rdi, 128
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 112
sub rax, rdi
mov rax, [rax]
pop rdi
xor rdx, rdx
cmp rax, rdi
setg dl
mov rax, rdx
test rax, rax
jz compress_L16
mov rax, rbp
mov rdi, 128
sub rax, rdi
push rax
mov rax, rbp
mov rdi, 112
sub rax, rdi
mov rax, [rax]
pop rdi
mov [rdi], rax
mov rax, rbp
mov rdi, 136
sub rax, rdi
push rax
mov rax, rbp
mov rdi, 104
sub rax, rdi
mov rax, [rax]
pop rdi
mov [rdi], rax
jmp compress_L17
compress_L16:
compress_L17:
mov rax, rbp
mov rdi, 104
sub rax, rdi
push rax
mov rax, 1
push rax
mov rax, rbp
mov rdi, 104
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
mov [rdi], rax
compress_L11:
mov rax, rbp
mov rdi, 56
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 104
sub rax, rdi
mov rax, [rax]
pop rdi
xor rdx, rdx
cmp rax, rdi
setl dl
mov rax, rdx
test rax, rax
jnz compress_L10
mov rax, 3
push rax
mov rax, rbp
mov rdi, 128
sub rax, rdi
mov rax, [rax]
pop rdi
xor rdx, rdx
cmp rax, rdi
setg dl
mov rax, rdx
test rax, rax
jz compress_L18
mov rax, 0
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
push rax
mov rax, 255
pop rdi
mov [rdi], al
mov rax, 1
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
push rax
mov rax, 63
push rax
mov rax, rbp
mov rdi, 128
sub rax, rdi
mov rax, [rax]
pop rdi
and rax, rdi
push rax
mov rax, 6
push rax
mov rax, 1023
push rax
mov rax, rbp
mov rdi, 136
sub rax, rdi
mov rax, [rax]
pop rdi
and rax, rdi
pop rdi
mov rcx, rdi
shl rax, cl
pop rdi
or rax, rdi
pop rdi
mov [rdi], al
mov rax, 2
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
push rax
mov rax, 2
push rax
mov rax, 1023
push rax
mov rax, rbp
mov rdi, 136
sub rax, rdi
mov rax, [rax]
pop rdi
and rax, rdi
pop rdi
mov rcx, rdi
shr rax, cl
pop rdi
mov [rdi], al
mov rax, write
push rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
push rax
mov rax, 3
push rax
pop rdx
pop rsi
pop rdi
pop rax
call rax
jmp compress_L19
compress_L18:
mov rax, rbp
mov rdi, 128
sub rax, rdi
push rax
mov rax, 1
pop rdi
mov [rdi], rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 96
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 80
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
push rax
pop rdi
xor rax, rax
mov al, [rdi]
pop rdi
mov [rdi], al
mov rax, 255
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
xor rax, rax
mov al, [rdi]
pop rdi
xor rdx, rdx
cmp rax, rdi
sete dl
mov rax, rdx
test rax, rax
jz compress_L20
mov rax, 1
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
push rax
mov rax, 0
pop rdi
mov [rdi], al
mov rax, 2
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
push rax
mov rax, 0
pop rdi
mov [rdi], al
mov rax, write
push rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
push rax
mov rax, 3
push rax
pop rdx
pop rsi
pop rdi
pop rax
call rax
jmp compress_L21
compress_L20:
mov rax, write
push rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
push rax
mov rax, 1
push rax
pop rdx
pop rsi
pop rdi
pop rax
call rax
compress_L21:
compress_L19:
mov rax, rbp
mov rdi, 72
sub rax, rdi
push rax
mov rax, 0
pop rdi
mov [rdi], rax
jmp compress_L23
compress_L22:
mov rax, rbp
mov rdi, 32
sub rax, rdi
push rax
mov rax, rbp
mov rdi, 72
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 96
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 80
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
add rax, rdi
push rax
pop rdi
xor rax, rax
mov al, [rdi]
pop rdi
mov [rdi], rax
mov rax, 1024
push rax
mov rax, rbp
mov rdi, 56
sub rax, rdi
mov rax, [rax]
pop rdi
xor rdx, rdx
cmp rax, rdi
setl dl
mov rax, rdx
test rax, rax
jz compress_L24
mov rax, rbp
mov rdi, 56
sub rax, rdi
push rax
mov rax, 1
push rax
mov rax, rbp
mov rdi, 56
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
mov [rdi], rax
jmp compress_L25
compress_L24:
compress_L25:
mov rax, rbp
mov rdi, 64
sub rax, rdi
push rax
mov rax, 1
push rax
mov rax, rbp
mov rdi, 56
sub rax, rdi
mov rax, [rax]
pop rdi
sub rax, rdi
pop rdi
mov [rdi], rax
jmp compress_L27
compress_L26:
mov rax, rbp
mov rdi, 64
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 48
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
push rax
mov rax, 1
push rax
mov rax, rbp
mov rdi, 64
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 48
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
sub rax, rdi
push rax
pop rdi
xor rax, rax
mov al, [rdi]
pop rdi
mov [rdi], al
mov rax, rbp
mov rdi, 64
sub rax, rdi
push rax
mov rax, 1
push rax
mov rax, rbp
mov rdi, 64
sub rax, rdi
mov rax, [rax]
pop rdi
sub rax, rdi
pop rdi
mov [rdi], rax
compress_L27:
mov rax, 0
push rax
mov rax, rbp
mov rdi, 64
sub rax, rdi
mov rax, [rax]
pop rdi
xor rdx, rdx
cmp rax, rdi
setg dl
mov rax, rdx
test rax, rax
jnz compress_L26
mov rax, rbp
mov rdi, 48
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 32
sub rax, rdi
mov rax, [rax]
pop rdi
mov [rdi], al
mov rax, rbp
mov rdi, 72
sub rax, rdi
push rax
mov rax, 1
push rax
mov rax, rbp
mov rdi, 72
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
mov [rdi], rax
compress_L23:
mov rax, rbp
mov rdi, 128
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 72
sub rax, rdi
mov rax, [rax]
pop rdi
xor rdx, rdx
cmp rax, rdi
setl dl
mov rax, rdx
test rax, rax
jnz compress_L22
mov rax, rbp
mov rdi, 96
sub rax, rdi
push rax
mov rax, rbp
mov rdi, 128
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 96
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
mov [rdi], rax
compress_L9:
mov rax, rbp
mov rdi, 88
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 96
sub rax, rdi
mov rax, [rax]
pop rdi
xor rdx, rdx
cmp rax, rdi
setl dl
mov rax, rdx
test rax, rax
jnz compress_L8
mov rax, 0
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
push rax
mov rax, 255
pop rdi
mov [rdi], al
mov rax, 1
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
push rax
mov rax, 1
pop rdi
mov [rdi], al
mov rax, 2
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
push rax
mov rax, 0
pop rdi
mov [rdi], al
mov rax, write
push rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
push rax
mov rax, 3
push rax
pop rdx
pop rsi
pop rdi
pop rax
call rax
mov rsp, rbp
pop rbp
ret
decompress:
push rbp
mov rbp, rsp
push rdi
push rsi
xor rax, rax
push rax
push rax
push rax
push rax
push rax
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
push rax
mov rax, malloc
push rax
mov rax, 20
push rax
mov rax, 1
pop rdi
mov rcx, rdi
shl rax, cl
push rax
pop rdi
pop rax
call rax
pop rdi
mov [rdi], rax
mov rax, rbp
mov rdi, 40
sub rax, rdi
push rax
mov rax, malloc
push rax
mov rax, 2
push rax
pop rdi
pop rax
call rax
pop rdi
mov [rdi], rax
jmp decompress_L29
decompress_L28:
mov rax, 255
push rax
mov rax, rbp
mov rdi, 40
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
xor rax, rax
mov al, [rdi]
pop rdi
xor rdx, rdx
cmp rax, rdi
sete dl
mov rax, rdx
test rax, rax
jz decompress_L30
mov rax, read
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 40
sub rax, rdi
mov rax, [rax]
push rax
mov rax, 2
push rax
pop rdx
pop rsi
pop rdi
pop rax
call rax
mov rax, rbp
mov rdi, 48
sub rax, rdi
push rax
mov rax, 63
push rax
mov rax, rbp
mov rdi, 40
sub rax, rdi
mov rax, [rax]
mov rax, [rax]
pop rdi
and rax, rdi
pop rdi
mov [rdi], rax
mov rax, rbp
mov rdi, 56
sub rax, rdi
push rax
mov rax, 1023
push rax
mov rax, 6
push rax
mov rax, rbp
mov rdi, 40
sub rax, rdi
mov rax, [rax]
mov rax, [rax]
pop rdi
mov rcx, rdi
shr rax, cl
pop rdi
and rax, rdi
pop rdi
mov [rdi], rax
mov rax, 0
push rax
mov rax, rbp
mov rdi, 48
sub rax, rdi
mov rax, [rax]
pop rdi
xor rdx, rdx
cmp rax, rdi
sete dl
mov rax, rdx
test rax, rax
jz decompress_L32
mov rax, rbp
mov rdi, 32
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
push rax
mov rax, 255
pop rdi
mov [rdi], al
mov rax, rbp
mov rdi, 32
sub rax, rdi
push rax
mov rax, 1
push rax
mov rax, rbp
mov rdi, 32
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
mov [rdi], rax
jmp decompress_L33
decompress_L32:
mov rax, 1
push rax
mov rax, rbp
mov rdi, 48
sub rax, rdi
mov rax, [rax]
pop rdi
xor rdx, rdx
cmp rax, rdi
sete dl
mov rax, rdx
test rax, rax
jz decompress_L34
mov rax, write
push rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 32
sub rax, rdi
mov rax, [rax]
push rax
pop rdx
pop rsi
pop rdi
pop rax
call rax
mov rax, 0
mov rsp, rbp
pop rbp
ret
jmp decompress_L35
decompress_L34:
mov rax, rbp
mov rdi, 64
sub rax, rdi
push rax
mov rax, 0
pop rdi
mov [rdi], rax
jmp decompress_L37
decompress_L36:
mov rax, rbp
mov rdi, 64
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 32
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
add rax, rdi
push rax
mov rax, 1
push rax
mov rax, rbp
mov rdi, 56
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 64
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 32
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
add rax, rdi
pop rdi
sub rax, rdi
pop rdi
sub rax, rdi
push rax
pop rdi
xor rax, rax
mov al, [rdi]
pop rdi
mov [rdi], al
mov rax, rbp
mov rdi, 64
sub rax, rdi
push rax
mov rax, 1
push rax
mov rax, rbp
mov rdi, 64
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
mov [rdi], rax
decompress_L37:
mov rax, rbp
mov rdi, 48
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 64
sub rax, rdi
mov rax, [rax]
pop rdi
xor rdx, rdx
cmp rax, rdi
setl dl
mov rax, rdx
test rax, rax
jnz decompress_L36
mov rax, rbp
mov rdi, 32
sub rax, rdi
push rax
mov rax, rbp
mov rdi, 48
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 32
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
mov [rdi], rax
decompress_L35:
decompress_L33:
jmp decompress_L31
decompress_L30:
mov rax, rbp
mov rdi, 32
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
push rax
mov rax, rbp
mov rdi, 40
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
xor rax, rax
mov al, [rdi]
pop rdi
mov [rdi], al
mov rax, rbp
mov rdi, 32
sub rax, rdi
push rax
mov rax, 1
push rax
mov rax, rbp
mov rdi, 32
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
mov [rdi], rax
decompress_L31:
decompress_L29:
mov rax, 0
push rax
mov rax, read
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 40
sub rax, rdi
mov rax, [rax]
push rax
mov rax, 1
push rax
pop rdx
pop rsi
pop rdi
pop rax
call rax
pop rdi
xor rdx, rdx
cmp rax, rdi
setg dl
mov rax, rdx
test rax, rax
jnz decompress_L28
mov rax, write
push rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 32
sub rax, rdi
mov rax, [rax]
push rax
pop rdx
pop rsi
pop rdi
pop rax
call rax
mov rax, 0
mov rsp, rbp
pop rbp
ret
mov rsp, rbp
pop rbp
ret
main:
push rbp
mov rbp, rsp
push rdi
push rsi
xor rax, rax
push rax
push rax
push rax
mov rax, 4
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
pop rdi
xor rdx, rdx
cmp rax, rdi
setne dl
mov rax, rdx
test rax, rax
jz main_L38
mov rax, puts
push rax
jmp main_L41
main_L40:
db "usage: juicer d|c infile outfile"
db 0
main_L41:
mov rax, main_L40
push rax
pop rdi
pop rax
call rax
mov rax, putch
push rax
mov rax, 10
push rax
pop rdi
pop rax
call rax
mov rax, 0
mov rsp, rbp
pop rbp
ret
jmp main_L39
main_L38:
main_L39:
mov rax, rbp
mov rdi, 16
sub rax, rdi
push rax
mov rax, nextarg
push rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
pop rax
call rax
pop rdi
mov [rdi], rax
mov rax, rbp
mov rdi, 40
sub rax, rdi
push rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
xor rax, rax
mov al, [rdi]
pop rdi
mov [rdi], rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
push rax
mov rax, nextarg
push rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
pop rax
call rax
pop rdi
mov [rdi], rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
push rax
mov rax, open
push rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
push rax
mov rax, 0
push rax
pop rsi
pop rdi
pop rax
call rax
pop rdi
mov [rdi], rax
mov rax, 0
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
pop rdi
xor rdx, rdx
cmp rax, rdi
setle dl
mov rax, rdx
test rax, rax
jz main_L42
mov rax, puts
push rax
jmp main_L45
main_L44:
db "Unable to open file"
db 0
main_L45:
mov rax, main_L44
push rax
pop rdi
pop rax
call rax
mov rax, putch
push rax
mov rax, 10
push rax
pop rdi
pop rax
call rax
mov rax, 0
mov rsp, rbp
pop rbp
ret
jmp main_L43
main_L42:
main_L43:
mov rax, rbp
mov rdi, 16
sub rax, rdi
push rax
mov rax, nextarg
push rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
pop rax
call rax
pop rdi
mov [rdi], rax
mov rax, rbp
mov rdi, 32
sub rax, rdi
push rax
mov rax, creat
push rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
pop rax
call rax
pop rdi
mov [rdi], rax
mov rax, 0
push rax
mov rax, rbp
mov rdi, 32
sub rax, rdi
mov rax, [rax]
pop rdi
xor rdx, rdx
cmp rax, rdi
setle dl
mov rax, rdx
test rax, rax
jz main_L46
mov rax, puts
push rax
jmp main_L49
main_L48:
db "Unable to create file"
db 0
main_L49:
mov rax, main_L48
push rax
pop rdi
pop rax
call rax
mov rax, putch
push rax
mov rax, 10
push rax
pop rdi
pop rax
call rax
mov rax, close
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
pop rax
call rax
mov rax, 0
mov rsp, rbp
pop rbp
ret
jmp main_L47
main_L46:
main_L47:
jmp main_L53
main_L52:
db "d"
db 0
main_L53:
mov rax, main_L52
push rax
pop rdi
xor rax, rax
mov al, [rdi]
push rax
mov rax, rbp
mov rdi, 40
sub rax, rdi
push rax
pop rdi
xor rax, rax
mov al, [rdi]
pop rdi
xor rdx, rdx
cmp rax, rdi
sete dl
mov rax, rdx
test rax, rax
jz main_L50
mov rax, decompress
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 32
sub rax, rdi
mov rax, [rax]
push rax
pop rsi
pop rdi
pop rax
call rax
jmp main_L51
main_L50:
jmp main_L57
main_L56:
db "c"
db 0
main_L57:
mov rax, main_L56
push rax
pop rdi
xor rax, rax
mov al, [rdi]
push rax
mov rax, rbp
mov rdi, 40
sub rax, rdi
push rax
pop rdi
xor rax, rax
mov al, [rdi]
pop rdi
xor rdx, rdx
cmp rax, rdi
sete dl
mov rax, rdx
test rax, rax
jz main_L54
mov rax, compress
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 32
sub rax, rdi
mov rax, [rax]
push rax
pop rsi
pop rdi
pop rax
call rax
jmp main_L55
main_L54:
mov rax, puts
push rax
jmp main_L59
main_L58:
db "unrecognized mode"
db 0
main_L59:
mov rax, main_L58
push rax
pop rdi
pop rax
call rax
mov rax, putch
push rax
mov rax, 10
push rax
pop rdi
pop rax
call rax
mov rax, close
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
pop rax
call rax
mov rax, close
push rax
mov rax, rbp
mov rdi, 32
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
pop rax
call rax
mov rax, 0
mov rsp, rbp
pop rbp
ret
main_L55:
main_L51:
mov rax, close
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
pop rax
call rax
mov rax, close
push rax
mov rax, rbp
mov rdi, 32
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
pop rax
call rax
mov rax, 0
mov rsp, rbp
pop rbp
ret
mov rsp, rbp
pop rbp
ret
