; this code was generated by a tool.
bits 64

getchar:
push rbp
mov rbp, rsp
xor rax, rax
push rax
jmp getchar_L1
getchar_L0:
getchar_L1:
mov rax, 1
neg rax
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
push rax
mov rax, getch
push rax
pop rax
call rax
pop rdi
mov [rdi], rax
pop rdi
xor rdx, rdx
cmp rax, rdi
sete dl
mov rax, rdx
test rax, rax
jnz getchar_L0
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
mov rsp, rbp
pop rbp
ret
mov rsp, rbp
pop rbp
ret
str_is_equal:
push rbp
mov rbp, rsp
push rdi
push rsi
xor rax, rax
jmp str_is_equal_L3
str_is_equal_L2:
mov rax, 0
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
xor rax, rax
mov al, [rdi]
pop rdi
xor rdx, rdx
cmp rax, rdi
sete dl
mov rax, rdx
test rax, rax
jz str_is_equal_L4
mov rax, 1
mov rsp, rbp
pop rbp
ret
jmp str_is_equal_L5
str_is_equal_L4:
str_is_equal_L5:
mov rax, rbp
mov rdi, 8
sub rax, rdi
push rax
mov rax, 1
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
mov [rdi], rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
push rax
mov rax, 1
push rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
mov [rdi], rax
str_is_equal_L3:
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
xor rax, rax
mov al, [rdi]
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
xor rax, rax
mov al, [rdi]
pop rdi
xor rdx, rdx
cmp rax, rdi
sete dl
mov rax, rdx
test rax, rax
jnz str_is_equal_L2
mov rax, 0
mov rsp, rbp
pop rbp
ret
mov rsp, rbp
pop rbp
ret
puts:
push rbp
mov rbp, rsp
push rdi
xor rax, rax
jmp puts_L7
puts_L6:
mov rax, putch
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
xor rax, rax
mov al, [rdi]
push rax
pop rdi
pop rax
call rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
push rax
mov rax, 1
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
mov [rdi], rax
puts_L7:
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
xor rax, rax
mov al, [rdi]
test rax, rax
jnz puts_L6
mov rsp, rbp
pop rbp
ret
fputs:
push rbp
mov rbp, rsp
push rdi
push rsi
xor rax, rax
push rax
jmp fputs_L9
fputs_L8:
mov rax, fputch
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
push rax
pop rsi
pop rdi
pop rax
call rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
push rax
mov rax, 1
push rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
mov [rdi], rax
fputs_L9:
mov rax, rbp
mov rdi, 24
sub rax, rdi
push rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
xor rax, rax
mov al, [rdi]
pop rdi
mov [rdi], rax
test rax, rax
jnz fputs_L8
mov rsp, rbp
pop rbp
ret
_mul:
push rbp
mov rbp, rsp
push rdi
push rsi
xor rax, rax
push rax
jmp _mul_L11
_mul_L10:
mov rax, rbp
mov rdi, 24
sub rax, rdi
push rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
mov [rdi], rax
_mul_L11:
mov rax, 0
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
pop rdi
xor rdx, rdx
cmp rax, rdi
setg dl
mov rax, rdx
test rax, rax
jnz _mul_L10
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
mov rsp, rbp
pop rbp
ret
mov rsp, rbp
pop rbp
ret
atoi:
push rbp
mov rbp, rsp
push rdi
xor rax, rax
push rax
push rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
xor rax, rax
mov al, [rdi]
pop rdi
mov [rdi], rax
jmp atoi_L13
atoi_L12:
mov rax, rbp
mov rdi, 24
sub rax, rdi
push rax
mov rax, _mul
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
push rax
mov rax, 10
push rax
pop rsi
pop rdi
pop rax
call rax
pop rdi
mov [rdi], rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
push rax
jmp atoi_L15
atoi_L14:
db "0"
db 0
atoi_L15:
mov rax, atoi_L14
push rax
pop rdi
xor rax, rax
mov al, [rdi]
push rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
pop rdi
sub rax, rdi
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
mov [rdi], rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
push rax
mov rax, 1
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
mov [rdi], rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
xor rax, rax
mov al, [rdi]
pop rdi
mov [rdi], rax
atoi_L13:
jmp atoi_L17
atoi_L16:
db "9"
db 0
atoi_L17:
mov rax, atoi_L16
push rax
pop rdi
xor rax, rax
mov al, [rdi]
push rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
pop rdi
xor rdx, rdx
cmp rax, rdi
setle dl
mov rax, rdx
push rax
jmp atoi_L19
atoi_L18:
db "0"
db 0
atoi_L19:
mov rax, atoi_L18
push rax
pop rdi
xor rax, rax
mov al, [rdi]
push rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
pop rdi
xor rdx, rdx
cmp rax, rdi
setge dl
mov rax, rdx
pop rdi
and rax, rdi
test rax, rax
jnz atoi_L12
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
mov rsp, rbp
pop rbp
ret
mov rsp, rbp
pop rbp
ret
next_arg:
push rbp
mov rbp, rsp
push rdi
xor rax, rax
jmp next_arg_L21
next_arg_L20:
mov rax, rbp
mov rdi, 8
sub rax, rdi
push rax
mov rax, 1
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
mov [rdi], rax
next_arg_L21:
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
xor rax, rax
mov al, [rdi]
test rax, rax
jnz next_arg_L20
mov rax, 1
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
mov rsp, rbp
pop rbp
ret
mov rsp, rbp
pop rbp
ret
main:
push rbp
mov rbp, rsp
push rdi
push rsi
xor rax, rax
push rax
push rax
push rax
push rax
push rax
push rax
mov rax, rbp
mov rdi, 48
sub rax, rdi
push rax
mov rax, brk
push rax
mov rax, 1
neg rax
push rax
pop rdi
pop rax
call rax
pop rdi
mov [rdi], rax
mov rax, brk
push rax
mov rax, 1024
push rax
mov rax, rbp
mov rdi, 48
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
push rax
pop rdi
pop rax
call rax
mov rax, 2
push rax
mov rax, rbp
mov rdi, 8
sub rax, rdi
mov rax, [rax]
pop rdi
xor rdx, rdx
cmp rax, rdi
sete dl
mov rax, rdx
test rax, rax
jz main_L22
mov rax, rbp
mov rdi, 40
sub rax, rdi
push rax
mov rax, creat
push rax
mov rax, next_arg
push rax
mov rax, rbp
mov rdi, 16
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
pop rax
call rax
push rax
pop rdi
pop rax
call rax
pop rdi
mov [rdi], rax
jmp main_L23
main_L22:
mov rax, puts
push rax
jmp main_L25
main_L24:
db "usage: write file"
db 0
main_L25:
mov rax, main_L24
push rax
pop rdi
pop rax
call rax
mov rax, putch
push rax
mov rax, 10
push rax
pop rdi
pop rax
call rax
mov rax, 0
mov rsp, rbp
pop rbp
ret
main_L23:
mov rax, rbp
mov rdi, 56
sub rax, rdi
push rax
mov rax, rbp
mov rdi, 48
sub rax, rdi
mov rax, [rax]
pop rdi
mov [rdi], rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
push rax
mov rax, 255
push rax
mov rax, getchar
push rax
pop rax
call rax
pop rdi
and rax, rdi
pop rdi
mov [rdi], rax
jmp main_L27
main_L26:
mov rax, 10
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
pop rdi
xor rdx, rdx
cmp rax, rdi
sete dl
mov rax, rdx
test rax, rax
jz main_L28
mov rax, rbp
mov rdi, 56
sub rax, rdi
mov rax, [rax]
push rax
mov rax, 0
pop rdi
mov [rdi], al
mov rax, rbp
mov rdi, 56
sub rax, rdi
push rax
mov rax, rbp
mov rdi, 48
sub rax, rdi
mov rax, [rax]
pop rdi
mov [rdi], rax
mov rax, str_is_equal
push rax
mov rax, rbp
mov rdi, 56
sub rax, rdi
mov rax, [rax]
push rax
jmp main_L33
main_L32:
db "."
db 0
main_L33:
mov rax, main_L32
push rax
pop rsi
pop rdi
pop rax
call rax
test rax, rax
jz main_L30
mov rax, rbp
mov rdi, 64
sub rax, rdi
push rax
mov rax, 1
pop rdi
mov [rdi], rax
jmp main_L31
main_L30:
mov rax, fputs
push rax
mov rax, rbp
mov rdi, 40
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 56
sub rax, rdi
mov rax, [rax]
push rax
pop rsi
pop rdi
pop rax
call rax
mov rax, fputch
push rax
mov rax, rbp
mov rdi, 40
sub rax, rdi
mov rax, [rax]
push rax
mov rax, 10
push rax
pop rsi
pop rdi
pop rax
call rax
mov rax, rbp
mov rdi, 32
sub rax, rdi
push rax
mov rax, 1
push rax
mov rax, rbp
mov rdi, 32
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
mov [rdi], rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
push rax
mov rax, 255
push rax
mov rax, getchar
push rax
pop rax
call rax
pop rdi
and rax, rdi
pop rdi
mov [rdi], rax
main_L31:
jmp main_L29
main_L28:
mov rax, rbp
mov rdi, 56
sub rax, rdi
mov rax, [rax]
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
pop rdi
mov [rdi], al
mov rax, rbp
mov rdi, 56
sub rax, rdi
push rax
mov rax, 1
push rax
mov rax, rbp
mov rdi, 56
sub rax, rdi
mov rax, [rax]
pop rdi
add rax, rdi
pop rdi
mov [rdi], rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
push rax
mov rax, 255
push rax
mov rax, getchar
push rax
pop rax
call rax
pop rdi
and rax, rdi
pop rdi
mov [rdi], rax
main_L29:
main_L27:
mov rax, 0
push rax
mov rax, rbp
mov rdi, 64
sub rax, rdi
mov rax, [rax]
pop rdi
xor rdx, rdx
cmp rax, rdi
sete dl
mov rax, rdx
push rax
mov rax, 0
push rax
mov rax, rbp
mov rdi, 24
sub rax, rdi
mov rax, [rax]
pop rdi
xor rdx, rdx
cmp rax, rdi
setne dl
mov rax, rdx
pop rdi
and rax, rdi
test rax, rax
jnz main_L26
mov rax, close
push rax
mov rax, rbp
mov rdi, 40
sub rax, rdi
mov rax, [rax]
push rax
pop rdi
pop rax
call rax
mov rax, 0
mov rsp, rbp
pop rbp
ret
mov rsp, rbp
pop rbp
ret
