; Petit: a 254-byte, platform-blind DOS stage-0 assembler
;
; Input is read from standard input. Generated bytes are written to standard output.
; DI is the output cursor at 0200h. A 256-entry symbol table begins at 7E00h.
#31C0# ; clear AX
#BF007E# ; point DI at the symbol table
#B90001# ; clear all 256 symbol entries
#F3AB# ; zero the symbol table
#BF0002# ; begin generated output at 0200h
:a ; dispatch the next source character
#E8#@e ; read the next source character
#3C21# ; ignore whitespace and control characters
#72F9# ; conditional branch
#0F84#@f ; '!' finishes the source
#3C3B# ; ';' begins a comment
#7417# ; conditional branch
#3C23# ; '#' begins hexadecimal bytes
#7426# ; conditional branch
#3C27# ; a quote begins literal text
#7418# ; conditional branch
#3C2A# ; '*' repeats a byte
#742B# ; conditional branch
#3C3A# ; ':' defines a symbol
#7468# ; conditional branch
#3C40# ; '@' emits or records a symbol reference
#742F# ; conditional branch
#AA# ; emit AL
#EBDA# ; continue the current scan or fixup loop
#E8#@e ; read the next source character
#3C0A# ; skip through the end of the comment line
#75F9# ; conditional branch
#EBD1# ; continue the current scan or fixup loop
#E8#@e ; read the next source character
#3C27# ; stop literal text at the closing quote
#74CA# ; conditional branch
#AA# ; emit AL
#EBF6# ; continue the current scan or fixup loop
#E8#@e ; read the next source character
#3C23# ; '#' begins hexadecimal bytes
#74C0# ; conditional branch
#E8#@c ; read one hexadecimal byte
#AA# ; emit AL
#EBF3# ; continue the current scan or fixup loop
#E8#@b ; read the next hexadecimal byte
#88C1# ; save the count or symbol name in CL
#E8#@b ; read the next hexadecimal byte
#F3AA# ; rep stosb byte ptr es:[di], al
#EBAE# ; continue the current scan or fixup loop
#E8#@e ; read the next source character
#88C1# ; save the count or symbol name in CL
#30E4# ; clear the high byte of the symbol index
#D1E0# ; scale the symbol index to a word offset
#93# ; move the symbol-table offset into BX
#8B87007E# ; load the symbol entry
#A90080# ; is this symbol already defined?
#750C# ; conditional branch
#AB# ; emit the resolved word
#89BF007E# ; remember the newest unresolved reference
#83AF007E02# ; store the reference word address
#EB8F# ; continue the current scan or fixup loop
#25FF7F# ; remove the defined flag
#F6C120# ; select relative or absolute fixup
#7407# ; conditional branch
#29F8# ; form a relative displacement
#83E802# ; make it relative to the end of the word
#EB03# ; continue the current scan or fixup loop
#2D0001# ; convert the COM load address to a file offset
#AB# ; emit the resolved word
#E9#@a ; return to the dispatcher
#E8#@e ; read the next source character
#88C1# ; save the count or symbol name in CL
#30E4# ; clear the high byte of the symbol index
#D1E0# ; scale the symbol index to a word offset
#93# ; move the symbol-table offset into BX
#8B97007E# ; mov dx, word ptr [bx + 0x7e00]
#89F8# ; start with the current output address
#0D0080# ; mark the symbol as defined
#8987007E# ; publish the symbol definition
#85D2# ; are unresolved references waiting?
#0F84#@a ; return to the dispatcher
#89D3# ; mov bx, dx
#8B17# ; load the next reference in the chain
#89F8# ; start with the current output address
#F6C120# ; select relative or absolute fixup
#7407# ; conditional branch
#29D8# ; form the reference displacement
#83E802# ; make it relative to the end of the word
#EB03# ; continue the current scan or fixup loop
#2D0001# ; convert the COM load address to a file offset
#8907# ; patch the reference word
#EBE1# ; continue the current scan or fixup loop
:b ; read one hexadecimal byte
#E8#@e ; read the next source character
:c ; combine two hexadecimal digits
#E8#@d ; convert the hexadecimal digit
#C0E004# ; move the high hexadecimal digit into place
#88C2# ; save the high nibble in DL
#E8#@e ; read the next source character
#E8#@d ; convert the hexadecimal digit
#08D0# ; combine the two nibbles
#C3# ; return
:d ; convert one hexadecimal digit
#2C30# ; convert '0'..'9'
#3C09# ; is it a decimal digit?
#7602# ; conditional branch
#2C07# ; adjust 'A'..'F'
#C3# ; return
:e ; read one source character without echo
#B408# ; DOS read-character function
#CD21# ; call DOS
#C3# ; return
:f ; write the generated image and exit
#89F9# ; compute generated byte count
#81E90002# ; subtract the 0200h output base
#BA0002# ; point DOS at the generated bytes
#BB0100# ; select standard output
#B440# ; DOS write-file function
#CD21# ; call DOS
#CD20# ; return to DOS

!
